version: "3.8"

services:
  order-app:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: order-service
    ports:
      - "50052:50052"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${ORDER_DB_USER}:${ORDER_DB_PASSWORD}@order-db:5432/${ORDER_DB_NAME}
    depends_on:
      order-db:
        condition: service_healthy
    networks:
      - microservices-network
    restart: unless-stopped
  
  order-db:
    image: postgres:15-alpine
    container_name: order-service-db
    environment:
      POSTGRES_USER: ${ORDER_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${ORDER_DB_PASSWORD:-123}
      POSTGRES_DB: ${ORDER_DB_NAME:-softam_order_service}
    ports:
      - "5437:5432"
    volumes:
      - order_service_data:/var/lib/postgresql/data
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ORDER_DB_USER:-postgres} -d ${ORDER_DB_NAME:-softam_order_service}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:        
  order_service_data: